### PR TITLE
Sort event log by lastTimestamp

### PR DESCRIPTION
**Pull request by nak3**
Currently debug.sh collects event log with -w and sleep 5 secs. It
seems that original author wanted to collect sorted event
log. However, actually It is possible by `--sort-by='.lastTimestamp'`
so that this PR changes to use --sort-by option and remove sleep 5 in
debug.sh.

### CODE REVIEW

**Comment by nekop** [comment]
>  It seems that original author wanted to collect sorted event

No it's for absolute timestamp, we don't want to see relative timestamp like `1h`.

The event is sorted by object name by default and it's actually useful. Sometimes sort by time is useful, especially when real time debugging but I prefer the current output in this script as this script is primarily designed for offline analysis.

**Comment by nak3** [comment]
I understand that you wanted to collect absolute time. But then, may I ask you why the script has `sleep 5` during collecting event logs?

**Comment by nekop** [comment]
Because if we kill it immediately we cannot get events from "oc get events -w &".

FYI the backgroud job then kill is already gone, we use timeout command now.

**Comment by nak3** [comment]
Ah, I see. Thank you. Closing this PR, then.

**Pull request closed without merging**
